
package com.ued1.punaisenpaholaisenmetsastys;

public enum Paikka {
    KYLA, ASEPAJA, HAARNISKAKAUPPA,
    TAISTELUAREENA, METSA, TAISTELU,
    ASEENOSTO, ASEENMYYNTI, HAARNISKANOSTO,
    MONSTERITAISTELU, MONSTERITAISTELUOHI
}
