
package com.ued1.punaisenpaholaisenmetsastys.logiikka;

/**
 * Enum Paikka määrittelee käytettävissä olevat paikka ja tilatiedot pelaajalle
 */
public enum Paikka {
    KYLA, ASEPAJA, HAARNISKAKAUPPA,
    TAISTELUAREENA, METSA, TAISTELU,
    ASEENOSTO, ASEENMYYNTI, HAARNISKANOSTO,
    MONSTERITAISTELU, MONSTERITAISTELUTAPPIO,
    TAISTELUAREENAEI, TAISTELUAREENATULOS,
    AREENATAISTELU, KAPAKKA, LUOLA,
    PAHOLAINEN, LOPPU, PAHOLAINENTAPPIO,
    KAPAKKAOSTO, KANNI, PARANTAJA, CASINO,
    PEUKKUPELI, PEUKKUTULOS, METSAPUPU
}
